# Generated by Django 4.2.1 on 2026-04-26 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_emailverificationcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_viewed',
            field=models.BooleanField(default=False, verbose_name='Просмотрен админом'),
        ),
    ]
