# Generated by Django 4.2.1 on 2026-04-22 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_booking_extra_bed_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='is_viewed',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Просмотрено администратором'),
        ),
    ]
