# Generated by Django 5.2.12 on 2026-03-27 21:46

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0001_initial'),
        ('cottages', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(help_text='Оценка от 1 до 5', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Оценка')),
                ('comment', models.TextField(help_text='Ваш отзыв о проживании', verbose_name='Комментарий')),
                ('is_approved', models.BooleanField(default=False, help_text='Отзыв прошел модерацию и опубликован', verbose_name='Одобрен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('booking', models.OneToOneField(help_text='Отзыв может быть оставлен только после завершенного бронирования', on_delete=django.db.models.deletion.CASCADE, related_name='review', to='bookings.booking', verbose_name='Бронирование')),
                ('cottage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='cottages.cottage', verbose_name='Домик')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
                'db_table': 'reviews',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['is_approved'], name='reviews_is_appr_807bf4_idx'), models.Index(fields=['rating'], name='reviews_rating_17e8a4_idx'), models.Index(fields=['cottage', 'is_approved'], name='reviews_cottage_c2e86c_idx')],
            },
        ),
    ]
