# Generated by Django 4.2.1 on 2026-04-02 00:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_booking_extra_bed_count'),
        ('cottages', '0006_alter_cottage_options'),
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='booking',
            field=models.OneToOneField(blank=True, help_text='Отзыв может быть оставлен только после завершенного бронирования', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='review', to='bookings.booking', verbose_name='Бронирование'),
        ),
        migrations.AlterField(
            model_name='review',
            name='cottage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='cottages.cottage', verbose_name='Домик'),
        ),
    ]
