# Generated by Django 4.2.1 on 2026-03-17 00:07

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название удобства')),
                ('icon', models.CharField(blank=True, default='', max_length=50, verbose_name='Иконка')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Удобство',
                'verbose_name_plural': 'Удобства',
                'db_table': 'amenities',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Cottage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название домика')),
                ('description', models.TextField(blank=True, default='', verbose_name='Описание')),
                ('address', models.CharField(blank=True, default='', max_length=300, verbose_name='Адрес')),
                ('price_per_night', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Цена за ночь (руб)')),
                ('capacity', models.IntegerField(default=2, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Вместимость (человек)')),
                ('bedrooms', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Количество спален')),
                ('bathrooms', models.DecimalField(decimal_places=1, default=1.0, max_digits=3, validators=[django.core.validators.MinValueValidator(0.5)], verbose_name='Количество ванных комнат')),
                ('area', models.IntegerField(default=30, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Площадь (м²)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('amenities', models.ManyToManyField(blank=True, related_name='cottages', to='cottages.amenity', verbose_name='Удобства')),
            ],
            options={
                'verbose_name': 'Домик',
                'verbose_name_plural': 'Домики',
                'db_table': 'cottages',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CottageImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='cottages/', verbose_name='Изображение')),
                ('is_main', models.BooleanField(default=False, verbose_name='Главное фото')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('cottage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='cottages.cottage', verbose_name='Домик')),
            ],
            options={
                'verbose_name': 'Изображение домика',
                'verbose_name_plural': 'Изображения домиков',
                'db_table': 'cottage_images',
                'ordering': ['-is_main', '-created_at'],
            },
        ),
    ]
