# Generated by Django 4.2.1 on 2026-04-01 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cottages', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cottage',
            old_name='name',
            new_name='title',
        ),
        migrations.AddField(
            model_name='cottage',
            name='house_type',
            field=models.CharField(choices=[('big', 'Большой дом'), ('small', 'Малый дом')], default='small', max_length=10, verbose_name='Тип домика'),
        ),
    ]
