# Generated by Django 4.2.1 on 2026-04-01 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cottages', '0002_rename_name_cottage_title_cottage_house_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cottage',
            name='amenities',
        ),
        migrations.AlterField(
            model_name='cottage',
            name='house_type',
            field=models.CharField(choices=[('big', '6-местный коттедж (Большой дом)'), ('small', '4-местный коттедж (Малый дом)')], default='small', max_length=10, verbose_name='Тип домика'),
        ),
        migrations.DeleteModel(
            name='Amenity',
        ),
    ]
