# Generated by Django 4.2.1 on 2026-04-01 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cottages', '0003_remove_cottage_amenities_alter_cottage_house_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cottage',
            name='address',
        ),
        migrations.RemoveField(
            model_name='cottage',
            name='bathrooms',
        ),
        migrations.RemoveField(
            model_name='cottage',
            name='description',
        ),
    ]
