# Generated by Django 4.2.1 on 2026-04-01 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cottages', '0004_remove_cottage_address_remove_cottage_bathrooms_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cottageimage',
            name='cottage',
        ),
        migrations.AddField(
            model_name='cottageimage',
            name='house_type',
            field=models.CharField(choices=[('big', '6-местный коттедж (Большой дом)'), ('small', '4-местный коттедж (Малый дом)')], default='big', max_length=10, verbose_name='Тип домика'),
        ),
    ]
