# Generated by Django 4.2.1 on 2026-04-01 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cottages', '0005_remove_cottageimage_cottage_cottageimage_house_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cottage',
            options={'ordering': ['id'], 'verbose_name': 'Домик', 'verbose_name_plural': 'Домики'},
        ),
    ]
