# Generated by Django 4.2.1 on 2026-04-22 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cottages', '0006_alter_cottage_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cottageimage',
            options={'ordering': ['display_order', '-is_main', '-created_at'], 'verbose_name': 'Изображение домика', 'verbose_name_plural': 'Изображения домиков'},
        ),
        migrations.AddField(
            model_name='cottageimage',
            name='display_order',
            field=models.IntegerField(default=0, verbose_name='Порядок сортировки'),
        ),
    ]
